version: '3'

# Define the services/containers to be run
services:

  backend:
    build: server
    ports:
      - 3000:3000
    links:
      - pg
    depends_on:
      - pg

  pg: #replace with another db
    image: postgres:alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER:'pipedrive'
      - POSTGRES_PASSWORD:'pipedrive'
      - POSTGRES_DB:'organizations'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql