CREATE ROLE pipedrive WITH LOGIN PASSWORD 'pipedrive';
GRANT ALL PRIVILEGES ON DATABASE organizations TO pipedrive;

CREATE TABLE IF NOT EXISTS ORGANIZATIONS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS RELATIONS (
    ID SERIAL PRIMARY KEY,
    START_ORG INT NOT NULL,
    END_ORG INT NOT NULL,
    TYPE VARCHAR(10) CHECK(TYPE = 'parent' OR TYPE = 'sister' OR TYPE = 'daughter')
);