CREATE DATABASE organizations;

-- ADD ROLES AND AUTH PART

CREATE TABLE IF NOT EXISTS 'ORGANIZATIONS' (
    'ID' SERIAL PRIMARY KEY,
    'NAME' VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS 'RELATIONS' (
    'ID' SERIAL PRIMARY KEY,
    'START_ORG' INT NOT NULL,
    'END_ORG' INT NOT NULL
    'TYPE' VARCHAR(10) CHECK('TYPE' = 'parent' OR 'TYPE' = 'sibling' OR 'TYPE' = 'daughter')
);

-- ADD FKs also cascading deletes